{% set version = "0.11" %}

package:
  name: piranha
  version: {{ version }}

source:
  fn: piranha-{{ version }}.tar.gz
  url: https://github.com/bluescarni/piranha/archive/v{{ version }}.tar.gz
  sha256: ab5782696a40888726c752c06a4b60783eda28ee4736b56083b96a53fd9a6230

build:
  number: 1002
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gmp
    - mpfr
    - boost-cpp
    - bzip2
    - zlib
  run:
    - gmp
    - mpfr
    - boost-cpp
    - bzip2
    - zlib

test:
  commands:
    - test -f $PREFIX/include/piranha/piranha.hpp

about:
  home: https://github.com/bluescarni/piranha
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'The Piranha computer algebra system.'

extra:
  recipe-maintainers:
    - isuruf
    - bluescarni
